# Dependabot configuration for Beatstream
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      # group minor & patch updates to a single grouped PR
      go-dependencies:
        update-types: ['minor', 'patch']

  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      # group dev & prod dependencies to a single grouped PR
      frontend-dev-dependencies:
        dependency-type: 'development'
        update-types: ['minor', 'patch']
      frontend-prod-dependencies:
        dependency-type: 'production'
        update-types: ['minor', 'patch']
