language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
before_script:
  - cp config/initializers/music_paths.rb.sample config/initializers/music_paths.rb
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake test
notifications:
  email:
    - ajk@ajk.fi
