# Dockerfile for publishing to hub.docker.com

# ---- Frontend build ----
FROM node:20.20.2 AS frontend

WORKDIR /app
COPY frontend/ .
RUN npm install && npm run build

# ---- Backend build ----
FROM golang:1.26.0 AS build

ARG VERSION=dev
ARG REVISION=unknown

WORKDIR /app

# requirements
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libtagc0-dev \
    && rm -rf /var/lib/apt/lists/*

# installs
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# copy frontend
COPY --from=frontend /app/dist /app/frontend/dist

# build
RUN CGO_ENABLED=1 go build -tags production \
    -ldflags="-X main.version=${VERSION} -X main.revision=${REVISION}" \
    -o /beatstream

# ---- Runtime ----
FROM golang:1.26.0 AS runtime

ENV MUSIC_PATH=/music

# requirements
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libtagc0-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /beatstream /beatstream

# expose default port by default
EXPOSE 8080

CMD ["/beatstream"]
