# Dockerfile for publishing to hub.docker.com

# ---- Frontend build ----
FROM --platform=$BUILDPLATFORM node:26.7.0 AS frontend

WORKDIR /app
COPY frontend/ .
RUN npm install && npm run build

# ---- Backend build ----
FROM golang:1.26.0 AS build

ARG VERSION=dev
ARG REVISION=unknown

WORKDIR /app

# installs
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# copy frontend
COPY --from=frontend /app/dist /app/frontend/dist

# build
RUN CGO_ENABLED=0 go build -tags production \
    -ldflags="-X main.version=${VERSION} -X main.revision=${REVISION}" \
    -o /beatstream

# ---- Runtime ----
FROM debian:13.3-slim AS runtime

ENV MUSIC_PATH=/music

COPY --from=build /beatstream /beatstream

# expose default port by default
EXPOSE 8080

CMD ["/beatstream"]
